name: Build Package

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    # For the sake of simplicity in testing, the Athena packaging program will temporarily run on Ubuntu-latest.
    # However, to ensure the stability of the packaging system, we will need to fix the Ubuntu version in the future.
    runs-on: ubuntu-latest

    # For the sake of simplicity in testing, the Athena packaging program will temporarily only package executable files for Python 3.8.
    # In the future, we will need to extend support to cover Python 3.8 through Python 3.12.
    steps:
      - name: Setup Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # Checkout the latest branch of Athena.
      - name: Checkout Athena
        uses: actions/checkout@v4
        with:
          submodules: true
          path: athena


      # Install Dependencies for Python
      - name: Install Dependencies for Python
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build

      # Build Athena
      - name: Build Athena
        working-directory: ./athena
        run: |
          python -m build
          python -m pip install dist/*.whl

      # Install Test
      - name: Run Test
        working-directory: ./athena/tests
        run: |
          bash run_all_test.sh
